name: Build Unity Project

on:
    workflow_dispatch:

jobs:
    build-unity-project:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                platform: [
                    StandaloneWindows64,
                    StandaloneOSX,
                    StandaloneLinux64,
                    WebGL
                ]
        
        name: Build Project
        steps:
            - name: Checkout
              uses: actions/cache@v3
              with:
                path: Library
                key: Library-gmtk2024-${{ matrix.platform }}
                restore-keys: |
                    Library-gmtk2024-
                    Library-
            - name: Cache
              uses: actions/checkout@v3
            - name: Build
              uses: game-ci/unity-builder@v4
              env:
                UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
              with:
                targetPlatform: ${{ matrix.platform }}
            - name: Upload Build to Artifact
              uses: actions/upload-artifact@v3
              with:
                name: Build
                path: build

    notify-discord:
        runs-on: ubuntu-latest
        needs: [
            build-unity-project,
        ]
        name: Notify Discord
        steps:
        - name: Notify Discord on Success
          if: success()
          uses: Ilshidur/action-discord@0.3.2
          env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_NOTIFICATION_WEBHOOK }}
            with:
            args:
                '✅ {{ EVENT_PAYLOAD.repository.full_name }} successfully built unity project'
        - name: Notify Discord on Failure
          if: failure()
          uses: Ilshidur/action-discord@0.3.2
          env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_NOTIFICATION_WEBHOOK }}
            with:
            args:
                '❌ {{ EVENT_PAYLOAD.repository.full_name }} failed to build unity project'
        - name: Notify Discord on Cancel
          if: cancelled()
          uses: Ilshidur/action-discord@0.3.2
          env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_NOTIFICATION_WEBHOOK }}
            with:
            args:
                '❌ {{ EVENT_PAYLOAD.repository.full_name }} cancelled build of unity project'
